import { StyleSheet } from 'react-native';

const SidebarStyles = StyleSheet.create({
  tabletSidebar: {
    backgroundColor: 'rgba(27, 42, 21, 0.95)', // Dark Matcha Green
    paddingTop: 50, 
    paddingBottom: 24,
    paddingHorizontal: 16,
    justifyContent: 'space-between',
    zIndex: 10,
    height: '100%',
    borderRightWidth: 1,
    borderRightColor: 'rgba(255, 255, 255, 0.1)',
  },
  tabletSidebarCollapsed: {
    paddingHorizontal: 8,
  },
  sidebarHeader: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  sidebarHeaderCollapsed: {
    paddingHorizontal: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    minWidth: 56,
    alignSelf: 'center',
    paddingVertical: 14,
  },
  brandGroup: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  brandLogo: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  brandLogoText: {
    fontSize: 22,
    color: '#34A853',
  },
  brandTitleGroup: {
    marginLeft: 12,
  },
  brandTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  brandSubtitle: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.6)',
    fontWeight: '600',
  },
  tabletNavContainer: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 24,
    paddingVertical: 20,
    paddingHorizontal: 10,
    gap: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    marginVertical: 10,
  },
  tabletNavContainerCollapsed: {
    paddingHorizontal: 4,
    alignItems: 'center',
    minWidth: 56,
    alignSelf: 'center',
  },
  tabletNavItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: 'transparent',
  },
  tabletNavItemActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  tabletNavItemCollapsed: {
    justifyContent: 'center',
    paddingHorizontal: 0,
    width: 52,
    height: 52,
    alignSelf: 'center',
  },
  tabletNavIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  tabletNavIcon: {
    fontSize: 18,
    color: '#34A853',
  },
  tabletNavIconActive: {
    color: '#34A853',
  },
  tabletNavLabel: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 15,
    fontWeight: '600',
    marginLeft: 14,
  },
  tabletNavLabelActive: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
    marginLeft: 14,
  },
  sidebarFooter: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  sidebarFooterCollapsed: {
    paddingHorizontal: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    minWidth: 56,
    alignSelf: 'center',
    paddingVertical: 14,
  },
  userProfileGroup: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarInitials: {
    color: '#34A853',
    fontWeight: '800',
    fontSize: 18,
  },
  userInfoText: {
    marginLeft: 12,
    flexShrink: 1,
  },
  userName: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  userRole: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
});

export default SidebarStyles;
